name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Make
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository -y https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Run Makefile
      run: |
        make
